/** Pełne biogramy zespołu - teksty ze strony amicare.pl */
export const BIOGRAMY: Record<string, string[]> = {
  'Dr n.med. Adam Rafał Poliwczak': [
    'Dr n.med. Adam Rafał Poliwczak to lekarz specjalista w zakresie kardiologii( od 2009 r.) oraz chorób wewnętrznych(od 2006r.)',
    'Studia medyczne ukończył na Wojskowej Akademii Medycznej w Łodzi, w 2003 r. uzyskał stopień doktora nauk medycznych.',
    'Obecnie jest w trakcie realizowania specjalizacji z farmakologii klinicznej.',
    'Posiada bogate doświadczenie w praktyce lekarskiej nieprzerwanie od 2002 r.',
    'Zajmował stanowisko asystenta w Klinice Chorób Wewnętrznych i Farmakologii Klinicznej Uniwersytetu Medycznego w Łodzi (2002 - 2009r.)',
    'Przez kolejne lata(2009 -2018 r.) pełnił funkcję adiunkta we wcześniej wspomnianym Instytucie.',
    'W latach 2018 - 2020 kierował  Zakładem Fizjologii Człowieka UM w Łodzi.',
    'Aktualnie związany z Kliniką Chorób Wewnętrznych i Rehabilitacji Kardiologicznej Uniwersytetu Medycznego w Łodzi.',
    'Doświadczenie w prowadzeniu badań klinicznych posiada od roku 2004 ; sprawował funkcję badacza w następujących próbach klinicznych:',
    'Migotanie przedsionków (2004 r.)',
    'Hiperlipidemia(2005 - 2007r.)',
    'Choroba Wieńcowa(2014 -2019r.)',
    'Nadciśnienie tętnicze (2021 - obecnie)',
    'Z Centrum Medycznym AmiCare współpracuje jako główny badacz od 2021 roku.',
    'Jest autorem kilkunastu publikacji naukowych w dziedzinie kardiologii, w tym m.in.:',
    '„Zasady wprowadzania do użycia leków odtwórczych. Biorównoważność polskich leków odtwórczych - simwastatyny i glimepirydu „(2006r.)',
    '„Heart rhythm turbulence and NT-proBNP in decompensated liver cirrhosis - a pilot study” (2011r.)',
    '„Cardiovascular risk assessment by electrocardiographic Holter monitoring in patients with chronic hepatitis C” (2020r.)',
    '„Safety assessment of chronic hepatitis C treatment using h-FABP and 24-hour ECG Holter Monitoring” (2020r.)  I wielu innych',
    'Zarezerwuj wizytę',
    'Telefonicznie: 42 28 90 250',
    'Adam Poliwczak - ZnanyLekarz.pl',
    'Cennik',
    'Usługa',
    'Cena',
    'Konsultacja kardiologiczna',
    '250zł',
    'Konsultacja kardiologiczna + ECHO',
    '350zł',
    'USG serca (echo serca)',
    '220zł',
    'EKG spoczynkowe',
    '40zł',
    'EKG spoczynkowe z opisem kardiologa',
    '90zł',
  ],
  'dr n. med. Dariusz Krzyczmanik': [
    'To specjalista chorób wewnętrznych oraz chorób zakaźnych z wieloletnim doświadczeniem klinicznym. Zajmuje się diagnostyką i leczeniem schorzeń internistycznych oraz zakaźnych u pacjentów dorosłych i dzieci.',
    'W swojej praktyce prowadzi również konsultacje gastrologiczne oraz wykonuje badania endoskopowe przewodu pokarmowego, takie jak gastroskopia i kolonoskopia. Przyjmuje pacjentów w placówkach medycznych na terenie Łodzi i okolic.',
    'Prowadzi diagnostykę i leczenie pacjentów dorosłych i dzieci.',
    'Zarezerwuj wizytę',
    'Telefonicznie: 42 28 90 250',
    'Umów wizytę',
    'Cennik',
    'Usługa',
    'cena',
    'Konsultacja Gastroenterologiczna',
    'od 300 do 350 zł',
    'Konsultacja Gastroenterologiczna w weekend',
    'od 400 do 450 zł',
  ],
  'dr n. med. Hubert Zatorski': [
    'dr n. med. Hubert Zatorski - Gastroenterolog',
    'W 2016 roku ukończył studia na kierunku lekarskim na Wydziale Lekarskim Uniwersytetu Medycznego w Łodzi.',
    'W 2022 roku obronił rozprawę doktorską pt. „Potencjał terapeutyczny hormonów inkretynowych oraz hormonów tkanki tłuszczowej w procesach zapalnych przewodu pokarmowego”. Studia doktoranckie odbywał w latach 2016-2021 w Zakładzie Biochemii Uniwersytetu Medycznego w Łodzi.',
    'W marcu 2024 roku ukończył specjalizację z gastroenterologii w Oddziale Klinicznym Gastroenterologii Ogólnej i Onkologicznej USK nr 1 im. N. Barlickiego w Łodzi. Od 2018 roku pracuje również jako asystent w Klinice Chorób Przewodu Pokarmowego Uniwersytetu Medycznego w Łodzi. Jest członkiem Polskiego Towarzystwa Gastroenterologicznego, European Society of Gastrointestinal Endoscopy (ESGE) oraz POLSPEN. Od 2019 roku pełni funkcję członka zarządu Sekcji Młodych Endoskopistów działającej przy Polskim Towarzystwie Gastroenterologicznym.',
    'Od 2014 roku regularnie uczestniczy w szkoleniach i konferencjach naukowych poświęconych najnowszym osiągnięciom w leczeniu chorób przewodu pokarmowego. W swojej pracy zawodowej zajmuje się diagnostyką i leczeniem nieswoistych chorób zapalnych jelit, chorób trzustki, SIBO, choroby uchyłkowej, choroby refluksowej przełyku oraz choroby wrzodowej żołądka i dwunastnicy.',
    'W trakcie pracy naukowej był wielokrotnie nagradzany za osiągnięcia naukowe. Otrzymał m.in. stypendium Ministra Nauki i Szkolnictwa Wyższego, Ministra Zdrowia, Miasta Łodzi oraz Naukowej Fundacji Polpharmy.',
    'Główne obszary pomocy:',
    'Choroba Leśniowskiego-Crohna',
    'Alergia pokarmowa',
    'Choroba wrzodowa',
    'Bóle brzucha',
    'Celiakia',
    'Choroby przewodu pokarmowego',
    'Choroby żołądka',
    'Choroby wątroby',
    'Choroba uchyłkowa jelit',
    'Choroby trzustki',
    'Biegunka',
    'W trakcie swojej pracy naukowej wielokrotnie byłem nagradzany za swoje osiągnięcia naukowe. Otrzymałem m.in. stypynedium Ministra Nauki i Szkolnictwa Wyższego (2014), stypendium Ministra Zdrowia (2015), stypendium naukowe Miasta Łodzi (2016), stypendium Naukowej Fundacji Polpharmy (2019).',
    'Praca zawodowa: W swojej pracy zawodowej zajmuje się diagnostyką i leczeniem nieswoistych chorób zapalnych jelit (choroby Leśniowskiego-Crohna oraz wrzodziejącego zapalenia jelita grubego), chorób trzustki (ostrego zapalenia trzustki oraz przewlekłego zapalenia trzustki), SIBO, choroby uchyłkowej, a także choroby refluksowej przełyku oraz choroby wrzodowej żołądka i dwunastnicy.',
    'Zarezerwuj wizytę',
    'Telefonicznie: 42 28 90 250',
    'Umów wizytę',
    'Cennik',
    'Usługa',
    'cena',
    'Konsultacja Gastroenterologiczna',
    'od 300 do 350 zł',
    'Konsultacja Gastroenterologiczna w weekend',
    'od 400 do 450 zł',
  ],
  'dr n. med. i n. o zdr. Danuta Domżał-Magrowska': [
    'Pani doktor Danuta Domżał - Magrowska jest lekarzem specjalistą gastroenterologii i chorób wewnętrznych. Z wyróżnieniem ukończyła wydział lekarski Uniwersytetu Medycznego w Łodzi w 2010r., a w 2020r. uzyskała stopień doktora nauk medycznych i nauk o zdrowiu (rozprawa doktorska o tematyce zespołu jelita nadwrażliwego). Jest autorką publikacji naukowych z zakresu gastroenterologii oraz prac przedstawianych na polskich i zagranicznych konferencjach naukowych. Jest członkinią Polskiego Towarzystwa Gastroenterologii.',
    'Pani doktor na co dzień pracuje w Oddziale Gastroenterologii Ogólnej i Onkologicznej USK nr 1 im. N. Barlickiego w Łodzi.',
    'W ramach konsultacji prowadzi porady z zakresu gastroenterologii, ze szczególnym uwzględnieniem nieswoistych chorób zapalnych jelit, zespołu jelita nadwrażliwego oraz chorób trzustki i dróg żółciowych, a także wykonuje badania endoskopowe- gastroskopie i kolonoskopie.',
    'Zarezerwuj wizytę',
    'Telefonicznie: 42 28 90 250',
    'Danuta Domżał-Magrowska - ZnanyLekarz.pl',
    'Cennik',
    'Usługa',
    'cena',
    'Konsultacja Gastroenterologiczna',
    'od 300 do 350 zł',
    'Konsultacja Gastroenterologiczna w weekend',
    'od 400 do 450 zł',
  ],
  'Dr n.med. Krzysztof Grzegorczyk': [
    'Dr n.med. Krzysztof Grzegorczyk jest lekarzem specjalistą w zakresie medycyny internistycznej(od 1984r.), gastroenterologii(od 1986r.) oraz chorób zakaźnych(od 2000r.)',
    'Studia medyczne ukończył jako absolwent Wojskowej Akademii Medycznej w Łodzi, a w roku 1986 uzyskał stopień doktora nauk medycznych.',
    'W latach 1978-1988 sprawował funkcję Młodszego Asystenta w Zakładzie Farmakologii Instytutu Nauk Przedklinicznych Wojskowej Akademii Medycznej w Łodzi, w kolejnych latach(1988-1998) pełnił obowiązki Starszego Asystenta Kliniki Internistycznej Wojskowej Akademii Medycznej w Łodzi, a w latach 1998-2008 Asystenta Profesora Kliniki Gastroenterologii WAM w Łodzi.',
    'Aktualnie zajmuje stanowisko kierownika Pracowni Endoskopii Leczniczej w Szpitalu im. Biegańskiego w Łodzi.',
    'Doświadczenie w prowadzeniu badań klinicznych jako współbadacz  posiada od 2007r. :',
    'Choroba Refluksowa Przełyku(2005-2007r.)',
    'Zespół Jelita Drażliwego(2009-2010r.)',
    'Choroba Leśniowskiego - Crohna(2017-2018r.)',
    'WZJG(2017-2018r.)',
    'Jest autorem i współautorem wielu oryginalnych artykułów, m.in.:',
    '„Stabilność witaminy C w próbkach pobieranego do analizy niekonserwowanego soku żołądkowego”',
    '„Zależność między wybranymi chorobami dolnego odcinka przewodu pokarmowego a zawartością witaminy C w błonie śluzowej odbytnicy”',
    '„Ocena stężeń witamin antyoksydacyjnych w osoczu krwi chorych z nowotworami pęcherzyka i dróg żółciowych”',
    '„Stan bariery antyoksydacyjnej u osób ze stanami przedrakowymi oraz rakiem dystalnego odcinka jelita grubego” i innych',
    'Zarezerwuj wizytę',
    'Telefonicznie: 42 28 90 250',
    'Krzysztof Grzegorczyk - ZnanyLekarz.pl',
    'Cennik',
    'Usługa',
    'cena',
    'Konsultacja Gastroenterologiczna',
    '350 zł',
    'Konsultacja Gastroenterologiczna w weekend',
    '450 zł',
  ],
  'dr n. med. Milena Padysz': [
    'dr n. med. Milena Padysz - Gastroenterolog',
    'W 2010 roku ukończyła Wydział Wojskowo-Lekarski Uniwersytetu Medycznego w Łodzi.',
    'Od początku swojej praktyki zawodowej związana jest z Kliniką Gastroenterologii Centralnego Szpitala Klinicznego Uniwersytetu Medycznego (dawniej USK im. WAM).',
    'W 2017 roku uzyskała tytuł specjalisty chorób wewnętrznych, a w 2021 roku specjalisty gastroenterologii. Na Uniwersytecie Medycznym w Łodzi ukończyła studia doktoranckie, a w 2019 roku obroniła pracę doktorską pt. „Ocena wybranych parametrów stanu zapalnego w korelacji z obrazem klinicznym choroby Leśniowskiego-Crohna”.',
    'W Roztoczańskiej Szkole Ultrasonografii ukończyła szkolenia z zakresu diagnostyki ultrasonograficznej narządów jamy brzusznej. Podczas pracy w Klinice Gastroenterologii zajmuje się rozpoznawaniem i leczeniem chorób przewodu pokarmowego, zwłaszcza nieswoistych chorób zapalnych jelit, choroby uchyłkowej jelita grubego, zaburzeń czynnościowych jelit oraz chorób przełyku, żołądka i pęcherzyka żółciowego.',
    'W pracowni endoskopii wykonuje badania endoskopowe górnego i dolnego odcinka przewodu pokarmowego. Zajmuje się również terapią biologiczną pacjentów z chorobą Leśniowskiego-Crohna i wrzodziejącym zapaleniem jelita grubego.',
    'Jest autorką publikacji w czasopismach polskich i zagranicznych. Bierze udział w licznych konferencjach naukowych w Polsce i za granicą. Jest członkinią Polskiego Towarzystwa Gastroenterologii. Do jej szczególnych zainteresowań należą zagadnienia dotyczące mikrobioty jelitowej, diagnozowanie dysbiozy jelitowej oraz leczenie SIBO.',
    'Główne obszary pomocy:',
    'Choroba Leśniowskiego-Crohna',
    'Wrzodziejące zapalenie jelita grubego',
    'Choroba uchyłkowa jelit',
    'Zespół jelita drażliwego',
    'Biegunka',
    'Choroby wątroby',
    'Choroba wrzodowa',
    'Refluks żołądkowo-przełykowy',
    'Zarezerwuj wizytę',
    'Telefonicznie: 42 28 90 250',
    'Umów wizytę',
    'Cennik',
    'Usługa',
    'cena',
    'Konsultacja Gastroenterologiczna',
    'od 300 do 350 zł',
    'Konsultacja Gastroenterologiczna w weekend',
    'od 400 do 450 zł',
  ],
  'Dr n. med. Rafał Drozda': [
    'Specjalista chirurgii ogólnej i onkologicznej. Specjalista gastroenterolog, proktolog.',
    'Dr n.med. Rafał Drozda Specjalista chirurgii ogólnej i onkologicznej. Specjalista gastroenterolog, proktolog.',
    'Pan doktor Rafał Drozda jest specjalistą chirurgii ogólnej i onkologicznej, który od lat zajmuje się przede wszystkim leczeniem chorób przewodu pokarmowego i proktologią. Jest również specjalistą gastroenterologii, czyli zajmuje się chorobami przewodu pokarmowego w szerokim znaczeniu, tzn. od diagnostyki po leczenie schorzeń nowotworowych, nienowotworowych i zapalnych całego układu pokarmowego. Posiada certyfikaty umiejętności endoskopowych, dzięki czemu wykonuje zarówno gastro-, jak i kolonoskopie i ultrasonograficznych jamy brzusznej. Poza tym wykonuje większość z szerokiej gamy operacji chirurgicznych. Przez wiele lat był biegłym sądowym z zakresu chirurgii ogólnej. Pracuję w Szpitalu w Turku na Oddziale Chirurgii Ogólnej, a także w pracowniach endoskopowych w Turku i w Szpitalu im. dr Wł.Biegańskiego w Łodzi. Prywatną praktykę lekarską prowadzi w gabinetach w Łodzi w Poddębicach i w Turku.',
    'W 2005 roku Pan doktor obronił doktorat na temat „Profilaktyki i leczenia raka jelita grubego”.',
    'Od tego czasu jest autorem i współautorem około 50 artykułów w ogólnopolskich i światowych czasopismach medycznych. Od 2008 roku jest również uznanym na świecie Badaczem w badaniach klinicznych.',
    'Praca naukowo-badawcza Pana doktora jako Głównego Badacza w AmiCare Centrum Medycznym została doceniona przez opiniotwórcze, amerykańskie czasopismo gastroenterologiczne Gastroenterology*. Prywatnie mąż i ojciec trzech synów, zapalony tenisista i narciarz.',
    '* Gastroenterology Available online 10 August 2022.Efficacy and Safety of Ivarmacitinib in Patients With Moderate-to-Severe, Active, Ulcerative Colitis: A Phase II Study',
    'Główne obszary pomocy:',
    'Hemoroidy',
    'Szczelina odbytu',
    'Nowotwory przewodu pokarmowego',
    'Choroby tarczycy',
    'Zapalenie trzustki',
    'Przepuklina',
    'Zapalenie żołądka',
    'Przetoki',
    'Zapalenie jelit',
    'Torbiele',
    'Zapalenie pęcherzyka żółciowego',
    'Zakrzep brzeżny odbytu',
    'Zarezerwuj wizytę',
    'Telefonicznie: 42 28 90 250',
    'Rafał Drozda - ZnanyLekarz.pl',
    'Cennik',
    'Usługa',
    'cena',
    'Konsultacja gastroenterologiczna ( dr n. med. Rafał Drozda',
    '350zł',
    'Konsultacja chirurgiczna ( dr n. med. Rafał Drozda',
    '350zł',
    'Konsultacja proktologiczna ( dr n. med. Rafał Drozda',
    '350zł',
    'Usługa',
    'cena',
    'Konsultacja chirurgiczna',
    '350zł',
    'Usunięcie szwów wraz z konsultacją',
    'od 450zł',
    'Wizyta kontrolna',
    '200zł',
    'Nacięcie zakrzepu brzeżnego',
    'od 700zł',
    'Zmiana opatrunku',
    'od 250zł',
    'Usuwanie znamion skórnych',
    '350-600zł (każdy kolejny 100zł)',
  ],
  'lek. Julia Banasik': [
    'lek. Julia Banasik - Gastroenterolog',
    'Absolwentka Wydziału Lekarskiego Uniwersytetu Medycznego w Łodzi. Po ukończeniu studiów pracowała w Podstawowej Opiece Zdrowotnej oraz Nocnej i Świątecznej Opiece Zdrowotnej, zdobywając doświadczenie w zakresie chorób internistycznych i całościowej opieki nad chorym.',
    'W 2019 roku uzyskała specjalizację z chorób wewnętrznych, obecnie w trakcie specjalizacji z gastroenterologii.',
    'W 2017 roku rozpoczęła studia doktoranckie na Uniwersytecie Medycznym w Łodzi, jest w trakcie zbierania materiałów do pracy doktorskiej pt. ,,Ocena włóknienia jelitowego u pacjentów z chorobą Leśniowskiego-Crohna w korelacji z kliniczną i biochemiczną aktywnością choroby”.',
    'Od początku pracy związana z Kliniką Gastroenterologii Uniwersyteckiego Szpitala Klinicznego im. WAM, w której od 2019 roku jest asystentem w grupie badawczo-dydaktycznej. Prowadzi seminaria i zajęcia kliniczne ze studentami oraz jest jednym z opiekunów koła naukowego przy Klinice Gastroenterologii. Autorka publikacji naukowych z zakresu chorób przewodu pokarmowego.',
    'W swojej pracy klinicznej zajmuje się diagnostyką i leczeniem chorób przewodu pokarmowego, a jej szczególnym obszarem zainteresowania są nieswoiste choroby zapalne jelit, choroba uchyłkowa jelita grubego, celiakia oraz choroby trzustki. Uczestniczy w konferencjach i szkoleniach z zakresu gastroenterologii. Członek Polskiego Towarzystwa Gastroenterologii.',
    'Główne obszary pomocy:',
    'Refluks żołądkowo-przełykowy',
    'Wrzodziejące zapalenie jelita grubego',
    'Choroba wrzodowa',
    'Zarezerwuj wizytę',
    'Telefonicznie: 42 28 90 250',
    'Umów wizytę',
    'Cennik',
    'Usługa',
    'cena',
    'Konsultacja Gastroenterologiczna',
    'od 300 do 350 zł',
    'Konsultacja Gastroenterologiczna w weekend',
    'od 400 do 450 zł',
  ],
  'lek. Łukasz Spadliński': [
    'lek. Łukasz Spadliński - Kardiolog',
    'Jest specjalistą kardiologii. Od 2019 roku pracuje w Klinice Kardiologii CSK UM w Łodzi, gdzie na co dzień zajmuje się diagnostyką oraz leczeniem chorób serca - od profilaktyki, przez hipercholesterolemię, nadciśnienie tętnicze, aż po chorobę wieńcową i niewydolność serca.',
    'W praktyce stawia na:',
    'rzetelną i dokładną diagnostykę',
    'indywidualne podejście do każdego pacjenta',
    'leczenie zgodne z aktualnymi wytycznymi kardiologicznymi',
    'jasne i zrozumiałe wyjaśnienie problemu zdrowotnego',
    'kompleksową opiekę - od konsultacji po plan leczenia',
    'Regularnie poszerza swoją wiedzę, uczestnicząc w konferencjach i szkoleniach kardiologicznych, aby zapewnić pacjentom opiekę na najwyższym poziomie. Zajmuje się leczeniem i profilaktyką i poprawa jakości życia.',
    'Zarezerwuj wizytę',
    'Telefonicznie: 42 28 90 250',
    'Umów wizytę',
    'Cennik',
    'Usługa',
    'Cena',
    'Konsultacja kardiologiczna',
    '250zł',
    'Konsultacja kardiologiczna + ECHO',
    '350zł',
    'USG serca (echo serca)',
    '220zł',
    'EKG spoczynkowe',
    '40zł',
    'EKG spoczynkowe z opisem kardiologa',
    '90zł',
  ],
  'lek. Magdalena Barańska': [
    'lek. Magdalena Barańska - Gastroenterolog',
    'W 2007 roku ukończyła Wydział Lekarski Uniwersytetu Medycznego w Łodzi. Specjalizację z zakresu chorób wewnętrznych odbywała pod kierownictwem prof. Anity Gąsiorowskiej w Oddziale Gastroenterologicznym Wojewódzkiego Szpitala Specjalistycznego w Zgierzu.',
    'W 2014 roku zdała Państwowy Egzamin Specjalizacyjny, uzyskując tytuł specjalisty chorób wewnętrznych. Od lutego 2014 roku związana jest z Oddziałem Klinicznym Gastroenterologii Ogólnej i Onkologicznej USK nr 1 im. N. Barlickiego w Łodzi, gdzie pracuje na stanowisku starszego asystenta.',
    'Jej zainteresowania zawodowe koncentrują się na diagnostyce i leczeniu nieswoistych chorób zapalnych jelit, a także ostrego i przewlekłego zapalenia trzustki oraz nowotworów tego narządu. Jest członkinią Polskiego Towarzystwa Gastroenterologicznego.  Główne obszary pomocy:',
    'Choroby żołądka',
    'Zespół jelita drażliwego',
    'Choroby trzustki',
    'Choroba Leśniowskiego-Crohna',
    'Choroba wrzodowa',
    'Zaparcia',
    'Refluks żołądkowo-przełykowy',
    'Choroba uchyłkowa jelit',
    'Bóle brzucha',
    'Biegunka',
    'Celiakia',
    'Wrzodziejące zapalenie jelita grubego',
    'Kamica żółciowa',
    'Zarezerwuj wizytę',
    'Telefonicznie: 42 28 90 250',
    'Umów wizytę',
    'Cennik',
    'Usługa',
    'cena',
    'Konsultacja Gastroenterologiczna',
    'od 300 do 350 zł',
    'Konsultacja Gastroenterologiczna w weekend',
    'od 400 do 450 zł',
  ],
  'lek. Michał Stasiak': [
    'lek. Michał Stasiak - Gastroenterolog',
    'W 2008 roku ukończył Wydział Lekarski Uniwersytetu Medycznego w Łodzi. W 2015 roku zdał Państwowy Egzamin Specjalizacyjny, uzyskując tytuł specjalisty chorób wewnętrznych.',
    'Pod kierownictwem dr. n. med. Marka Pazurka ukończył szkolenie specjalizacyjne w dziedzinie gastroenterologii. W dniu 9 lipca 2020 roku zdał Państwowy Egzamin Specjalizacyjny, uzyskując tytuł specjalisty gastroenterologii.',
    'Obszar jego zainteresowań zawodowych obejmuje choroby zapalne trzustki (ostre i przewlekłe zapalenie trzustki), nowotwory tego narządu oraz nieswoiste choroby zapalne jelit, w tym wrzodziejące zapalenie jelita grubego i chorobę Leśniowskiego-Crohna.',
    'Poza pracą kliniczną zajmuje się działalnością naukową, publikując artykuły w czasopismach medycznych, m.in. „Gastroenterologii Polskiej” i „Postępach Nauk Medycznych”. Jest członkiem Polskiego Towarzystwa Gastroenterologicznego oraz Polskiego Klubu Trzustkowego.',
    'Główne obszary pomocy:',
    'Choroby przewodu pokarmowego',
    'Wrzodziejące zapalenie jelita grubego',
    'Choroba Leśniowskiego-Crohna',
    'Choroby trzustki',
    'Choroby dróg żółciowych',
    'Celiakia',
    'Refluks żołądkowo-przełykowy',
    'Choroba wrzodowa',
    'Zespół jelita drażliwego',
    'Biegunka',
    'Zaparcia',
    'Zarezerwuj wizytę',
    'Telefonicznie: 42 28 90 250',
    'Umów wizytę',
    'Cennik',
    'Usługa',
    'cena',
    'Konsultacja Gastroenterologiczna',
    'od 300 do 350 zł',
    'Konsultacja Gastroenterologiczna w weekend',
    'od 400 do 450 zł',
  ],
  'Dominika Buczyńska': [
    'Psycholog',
    'Absolwentka Uniwersytetu Łódzkiego.',
    'Ukończyła psychologię, psychologię doradztwa zawodowego i organizacji oraz oligfrenopedagogika i integracja sensoryczna.',
    'Pracuje z dziećmi, młodzieżą i dorosłymi. Specjalizuje się w pracy z małymi dziećmi w zakresie wczesnego wspomagania rozwoju. Posiada uprawnienia do pracy z osobami ze specjalnymi potrzebami edukacyjnymi (niepełnosprawnością intelektualną, spektrum autyzmu, mutyzm). Jest również terapeutą integracji sensorycznej. Posiada uprawnienia z zakresu Treningu Umiejętności Społecznych. Prowadzi pomoc psychologiczną w zakresie: zaburzeń zachowania i emocji, problemów wychowawczych, konfliktów rówieśniczych, rozwiązywania konfliktów w grupie, adaptacji do nowego środowiska szkolnego. Udziela porad wychowawczych.',
    'Zarezerwuj wizytę',
    'Telefonicznie: 42 28 90 250',
    'Cennik',
    'Usługa',
    'cena',
    'Konsultacja psychologiczna',
    '230zł',
    'Konsultacja psychologiczna u dzieci',
    '230zł',
  ],
  'Dr hab n. med. Mariola Świderek-Matysiak': [
    'Dr hab n. med. Profesor Uczelni Mariola Świderek-Matysiak',
    'Dr hab n. med. Profesor Uczelni Mariola Świderek-Matysiak to lekarz specjalista w zakresie neurologii',
    '(od 2004 r.) oraz lekarz medycyny z ponad 25 - letnim stażem praktyki lekarskiej.',
    'Aktualnie obejmuje stanowisko  zastępcy kierownika Kliniki Neurologii Uniwersytetu Medycznego w Łodzi USK nr 1. im. N. Barlickiego oraz sprawuje funkcję adiunkta dydaktycznego( od 2015 r.)',
    'Dr hab n. med., Profesor Uczelni Mariola Świderek-Matysiak jest absolwentką Akademii Medycznej w Łodzi, którą ukończyła z wyróżnieniem. W  1998 r. rozpoczęła studia doktoranckie na rodzimej uczelni, a cztery lata później( 2002 rok) -  uzyskała stopień doktora nauk medycznych. Trzynaście lat później( 2015 r.) zdobyła habilitację. W roku 2022 nadano jej tytuł Profesora Uczelni.',
    'Związana z AmiCare od 2018 r. jako główny badacz oraz specjalista w dziedzinie neurologii.',
    'Ze względu na liczne zasługi w świecie nauki o układzie nerwowym i jego schorzeniach, jest laureatką wielu nagród, m.in.: Ministra Zdrowia, Nagrody Naukowej im. J. Śniadeckiego, Nagrody im. Jerzego Konorskiego Polskiego Towarzystwa Badań Układu Nerwowego i innych.',
    'Jest autorką oraz współautorką kilkunastu oryginalnych prac naukowych, w tym m.in.:',
    '„Siponimod w leczeniu postaci wtórnie postępującej stwardnienia rozsianego - opis przypadku” (2023r.)',
    '„Cerebrospinal Fluid Biomarkers in Differential Diagnosis of Multiple Sclerosis and Systemic Inflammatory Diseases with Central Nervous System Involvement” (2023r.)',
    '„The effectiveness of combination therapy of nucleotides and B vitamins in the reduction of pain associated with injuries of the roots and peripheral nerves” (2022r.)',
    '„Analiza profilu ekspresji microRNA w nieuronalnie róznicowancyh komórkach macierzystych w kontekście immunoregulacyjnej roli w autoimmunologicznym zapaleniu mózgu i rdzenia (EAE)”',
    'Posiada doświadczenie w prowadzeniu badań klinicznych jako główny badacz/współbadacz od 2002 roku, w takich schorzeniach jak:',
    'Migrena(2021 r. - obecnie)',
    'Stwardnienie rozsiane - (2002r. -  2016)',
    'Miastenia gravis(2021 r. - obecnie)',
  ],
  'Dr Joanna Kowalska-Majka': [
    'Dr Joanna Kowalska - Majka jest lekarzem specjalistą w zakresie reumatologii(od 2007 r.) oraz chorób wewnętrznych( I stopień - 1996r. ; II stopień - 2000 r.)',
    'Studia medyczne ukończyła jako absolwentka Wydziału Lekarskiego Uniwersytetu Medycznego w Łodzi.',
    'Obecnie współpracuje z pacjentami na Oddziale Reumatologicznym w Wojewódzkim Wielospecjalistycznym Centrum Onkologii i Traumatologii im. M. Kopernika w Łodzi oraz udziela prywatnych konsultacji w Centrum Medycznym zlokalizowanym również w Łodzi.',
    'Wspólnie z Dr n.med. Jolantą Lewandowicz jest współautorką oryginalnego artykułu dotyczącego szeroko pojętej dziedziny reumatologii :',
    '„Satisfaction and discontent of Polish patients with biological therapy of rheumatic diseases: results of a multi-center questionnaire study”',
    'opublikowanego w 2018 roku ;',
    'oraz oryginalnej pracy naukowej przedstawionej na XI Środkowoeuropejskim Kongresie Reumatologicznym',
    '„Satisfaction and dissatisfaction of patients with rheumatic diseases receiving biologics',
    '” (Praga, 2016 rok)',
    'Cennik',
    'Usługa',
    'cena',
    'Konsultacja reumatologiczna',
    '300zł',
    'USG barku',
    '200zł',
    'USG ręki',
    '200zł',
    'USG stawu kolanowego',
    '200zł',
    'USG stawu skokowego',
    '200zł',
    'USG stawu łokciowego',
    '200zł',
    'USG stawów barkowych',
    '300zł',
    'USG stawów kolanowych',
    '300zł',
    'USG stawów skokowych',
    '300zł',
    'Zarezerwuj wizytę',
    'Telefonicznie: 42 28 90 250',
    'Umów wizytę',
  ],
  'Dr Karolina Niczyporuk': [
    'to lekarz specjalista w dziedzinie otolaryngologii dziecięcej.',
    'Ukończyła studia medyczne na Wydziale Wojskowo - Lekarskim Uniwersytetu Medycznego w Łodzi.',
    'Aktualnie zajmuje stanowisko Młodszego Asystenta w Klinice Otolaryngologii Audiologii i Foniatrii Dziecięcej UCP im. Marii Konopnickiej w Łodzi.',
    'Jest członkiem Polskiego Towarzystwa Chirurgów Głowy i Szyi.',
    'Zajmuje się takimi schorzeniami jak:',
    'Ostre Zapalenie Zatok',
    'Zapalenie Gardła',
    'Ból zatok',
    'Zapalenie krtani',
    'Zapalenie ucha i inne',
  ],
  'Dr Katarzyna Przybyłowska-Kustosik': [
    'Dr Katarzyna Przybyłowska - Kustosik to lekarz specjalista w zakresie psychiatrii.',
    'Dr Katarzyna Przybyłowska- Kustosik',
    'ukończyła studia medyczne na Wydziale Lekarskim Uniwersytetu Medycznego w Białymstoku.',
    'W latach 2007-2015 pracowała z pacjentami w Specjalistycznym Psychiatrycznym ZOZ i J. Babińskiego w Łodzi.',
    'Od 2015 r. pełni funkcję Ordynatora Oddziału w Szpitalu im. J. Babińskiego w Łodzi.',
    'Diagnozuje i wdraża leczenie w takich chorobach jak:',
    'Depresja',
    'Schizofrenia',
    'Bezsenność',
    'Psychoza',
    'Uzależnienie od alkoholu',
    'Uzależnienie od narkotyków',
    'Choroba afektywna dwubiegunowa',
    'Nerwica i inne',
    'Ukończyła kurs psychoterapii w Instytucie Ericksonowskim w Łodzi, jak również uczestniczy w wielu konferencjach naukowych - zarówno tych krajowych, jak i zagranicznych.',
    'Posiada doświadczenie w branży badań klinicznych m.in. jako współbadacz w takich schorzeniach jak: schizofrenia, uzależnienie od alkoholu czy zaburzenia obsesyjno - kompulsywne.',
  ],
  'Dr n.med. Agnieszka Bała': [
    'to lekarz specjalista w zakresie medycyny internistycznej(od 2001r.) oraz farmakologii klinicznej(od 2015r.)',
    'Ukończyła studia medyczne jako absolwentka Wydziału Lekarskiego Akademii Medycznej w Łodzi, posiada również tytuł doktora nauk medycznych.',
    'W latach 1996-1997 odbyła staż w Zespole Opieki Zdrowotnej w Łodzi, a następnie sprawowała obowiązki Asystenta na Uniwersytecie Medycznym w Łodzi.',
    'Obecnie zajmuje stanowisko Adiunkta w Klinice Chorób Wewnętrznych oraz Farmakologii Klinicznej UM w Łodzi.',
    'W swojej praktyce lekarskiej zajmuje się diagnostyką oraz leczeniem m.in.:',
    'Chorób i wad serca',
    'Cukrzycy',
    'Infekcji( w tym górnych dróg oddechowych)',
    'Nadciśnienia tętniczego i wielu innych',
    'Z Centrum Medycznym AmiCare związana jako współbadacz od 2022 roku.',
    'Dr n.med. Agnieszka Bała jest autorem&współautorem licznych publikacji naukowych, w tym m.in.:',
    '„Treatment of heart failure in the elderly in Poland. The results of the Polish part of EURObservational Research Programme: The Heart Failure Pilot Survey” (2019r.) - opublikowanym w czasopiśmie „Advances in Clinical and Experimental Medicine”',
    '„Non - sustained ventricular tachycardia during treatment of genotype 3 chronic hepatitis C- a case report” (2016r.) - opublikowanym w czasopiśmie „Polski Merkuriusz Lekarski”',
    '„Wpływ długotrwałej terapii hipolipemizującej za pomocą simwastatyny i atorwastatyny oraz zmikronizowanej postaci fenofibratu na lipidy osocza i powstawanie kwasów żółciowych jako końcowego ogniwa utylizacji cholesterolu” (2008r.) - opublikowanym w czasopiśmie „Problemy Terapii Monitorowanej”',
    'Zarezerwuj wizytę',
    'Telefonicznie: 42 28 90 250',
    'Agnieszka Bała - ZnanyLekarz.pl',
    'Cennik',
    'Usługa',
    'cena',
    'Konsultacja u Internisty',
    '220zł',
  ],
  'Dr n. med. Aleksandra Bała-Wojsznis': [
    'to lekarz specjalista w zakresie dermatologii oraz wenerologii (I stopień - 2001r. ; II stopień- 2007 r.)',
    'Studia medyczne ukończyła na Wydziale Lekarskim Akademii Medycznej w Łodzi, w 2003 r. uzyskała tytuł doktora nauk medycznych.',
    'Od 1998 roku pracuje z pacjentami w Specjalistycznej Poradni Dermatologicznej w Szpitalu im Wł. Biegańskiego w Łodzi,a od 2021 roku udziela prywatnych konsultacji i porad medycznych w Centrum medycznym zlokalizowanym również w Łodzi.',
    'Posiada doświadczenie w prowadzeniu badań klinicznych jako współbadacz od 2008 roku, między innymi w takich schorzeniach jak:',
    'Atopowe Zapalenie  Skóry',
    'Łuszczyca',
    'Pokrzywka',
    'Owrzodzenia',
    'Jest autorem & współautorem kilkunastu publikacji naukowych obejmujących dziedzinę dermatologii, w tym m.in.:',
    '„Badania enzymów granulocytów wielojądrzastych obojętnochłonnych oraz poziomy ich inhibitorów w surowicy u chorych na liszaj płaski Wilsona” (2004r.)',
    '„Niskotemperaturowa ablacja (Coblation) - nowa metoda elektrochirurgicznego odmładzania skóry twarzy” (2004r.)',
    '„Liszaj czerwony płaski - etiopatogeneza, klinika i współczesne metody leczenia” (2003r.)',
    '„Łysienie androgenowe i plackowate - etiopatogeneza, obraz kliniczny oraz wybrane metody leczenia” (2003r.)',
  ],
  'Dr n.med. Dorota Czech': [
    'to lekarz specjalista w zakresie otolaryngologii - w szczególności dziecięcej (od 2018r.).',
    'Studia medyczne ukończyła jako absolwentka Wydziału Lekarskiego Uniwersytetu Medycznego w Łodzi, a następnie kontynuowała swoją ścieżkę edukacji na studiach doktoranckich UM w Łodzi, które przypieczętowała uzyskaniem stopnia doktora nauk medycznych.',
    'W latach 2007- 2014 sprawowała funkcję młodszego asystenta na Oddziale Otolaryngologii, Audiologii i Foniatrii Dziecięcej UCP CSK w Łodzi. Następnie zajmowała stanowisko Asystenta na UM w Łodzi( 2014 - 2018 r.) ; Starszego asystenta na Oddziale Otolaryngologii, Audiologii i Foniatrii Dziecięcej UCP CSK w Łodzi (2018 - 2021 r.), a obecnie Kierownika Kliniki Otolaryngologii Dziecięcej w Łodzi(2022r. - nadal)',
    'Dr n.med. Dorota Czech stale pogłębia swoją wiedzę, uczestnicząc w szkoleniach i konferencjach, dzięki czemu pacjenci objęci jej opieką mają dostęp do nowoczesnych metod leczenia oraz diagnostyki.',
    'Doświadczenie w prowadzeniu badań klinicznych posiada od 2015 roku; sprawowała funkcję współbadacza w takich próbach klinicznych jak:',
    'Dyspioza górnych dróg oddechowych związana z częstym spożyciem słodyczy zwiększa ryzyko astmy u dzieci z przewlekłym zapaleniem zatok przynosowych( 2015 - 2018r.)',
    'Badanie przeciwciał monoklonalnych w alergologii pediatrycznej( 2017 r. - 2018)',
    'Z Centrum Medycznym AmiCare związana od 2022 r. jako Główny Badacz w swojej specjalizacji.',
    'Jest współautorem  publikacji naukowych w dziedzinie laryngologii w tym m.in.:',
    '„Effect of an Intranasal Corticosteroid on Quality of Life and Local Microbiome in Young Children With Chronic Rhinosinusitis A Randomized Clinical Trial „ (2023r.)',
    '„The role of innate lymphoid cells in chronic rhinosinusitis severity in children: a cross-sectional study” (2023r.)',
    '„Upper-airway dysbiosis related to frequent sweets consumption increases the risk of asthma in children with chronic rhinosinusitis” (2021r.)',
    '„Zapalenie gardła i krtani - diagnostyka i leczenie” (2019r.)',
    '„Ocena występowania zaburzeń artykulacyjnych u dzieci z nawracającymi infekcjami górnych dróg oddechowych” (2011r.)',
  ],
  'Dr n. med. Izabela Kubińska': [
    'Lekarz pediatra, specjalista gastroenterologii.',
    'Ukończyła wydział lekarski na Uniwersytecie Medycznym w Łodzi, a specjalizację uzyskała w dziedzinie chorób dziecięcych i gastroenterologii, uzyskując ponadto stopień naukowy doktora nauk medycznych. Zdobywała doświadczenie w Instytucie Centrum Zdrowia Matki Polki w Łodzi, w Klinice Pediatrii Alergologii i Gastroenterologii na stanowisku starszego asystenta.',
    'Obecnie pracuje w Wojewódzkim Szpitalu Specjalistycznym im. M. Kopernika oraz w szpitalu im. dr J. Korczaka w Łodzi. Wykonuje badania endoskopowe górnego i dolnego odcinka przewodu pokarmowego ,badanie endosonograficzne trzustki zarówno u dzieci jak i dorosłych.',
    'Zajmuje się diagnostyką przewlekłych bólów brzucha u dzieci, leczeniem przewlekłego zaparcia stolca, nieswoistymi chorobami zapalnymi jelit, chorobą refluksową, diagnostyką i leczeniem niedoboru masy ciała, alergii i nietolerancji pokarmowych, celiakii oraz zaburzeniami karmienia niemowląt.  Szczególny nacisk kładzie na profilaktykę. Uważa, że najważniejsze dla zachowania dobrego zdrowia jest kształtowanie prawidłowych nawyków żywieniowych u dzieci. Farmakologia powinna stanowić uzupełnienie całościowego leczenia.  W Poradni Gastrologicznej zajmuje się leczeniem chorób u dzieci na tle psychosomatycznym. Jest specjalistką w dziedzinie terapii żywieniowo-farmakologicznej autyzmu, w którym często występują dolegliwości ze strony układu pokarmowego. Wie, że odpowiednio dobrane leczenie specjalistyczne jest niekiedy kluczowe dla nastroju, rozwoju i zachowania dziecka. Dzięki dokładnej diagnozie, wywiadom lekarskim i szerokiemu spojrzeniu na jego problemy, włącza leczenie dopasowane do indywidualnych potrzeb małego pacjenta.  Prywatnie jest mamą Kajetana, Juliana i Łucji. Z wieloma problemami wieku rozwojowego boryka się więc osobiście, dlatego dobrze rozumie potrzeby i problemy innych rodziców.',
    'Zarezerwuj wizytę',
    'Telefonicznie: 42 28 90 250',
    'Izabela Kubińska - ZnanyLekarz.pl',
    'Cennik',
    'Usługa',
    'cena',
    'Konsultacja Gastroenterologiczna',
    'od 300 do 350 zł',
    'Konsultacja Gastroenterologiczna w weekend',
    'od 400 do 450 zł',
  ],
  'Dr n.med. Jacek Przybyła': [
    'to lekarz specjalista w zakresie urologii.',
    'Studia medyczne ukończył jako absolwent Wydziału Lekarskiego Akademii Medycznej w Łodzi, w 2008 roku uzyskał tytuł specjalisty europejskiego w dziedzinie urologii,a w 2011 r. obronił tytuł doktora nauk medycznych.',
    'Ukończył studia podyplomowe na Wydziale Wojskowo - Lekarskim Akademii Medycznej w Łodzi w 2011 roku.',
    'Od 2006 roku posiada certyfikat w zakresie ultrasonografii układu moczowo - płciowego - wydany przez Polskie Towarzystwo Urologiczne.',
    'Oprócz tego posiada:',
    'Kurs laparoskopii ( Elancourt, Francja 2010 r.)',
    'Kurs endoskopii( San Francisco, USA 2010r. ; Mediolan, Włochy 2013 r.)',
    'Kursy z zakresu neurourologii( Klinika Urologii Akademii medycznej w Warszawie)',
    'Zdobył nagrodę Rektora Uniwersytetu Medycznego w Łodzi za najlepiej obronioną Pracę Doktorską w dziedzinach zabiegowych im. Prof.M.Stefanowskiego(2012 r.)',
    'Diagnozuje oraz wdraża leczenie w męskiej niepłodności w Klinice Leczenia Niepłodności Gameta - Szpital.',
    'Jest autorem&współautorem licznych publikacji naukowych w dziedzinie urologii w tym m.in.:',
    '„Prevalence, risk factors, prophylactic behavior, therapeutic behavior and state of knowledge regarding urinary tract infections among chosen population of nursing/midwifery students and Qualified nurses/midwifes from Medical University of Łódź” (2010 r.)',
    '„The analysis risk factors biochemical and clinical recurrence prostate carcinoma after radical prostatectomy” (2011r.)',
    '„Analiza wpływu poziomu wiedzy pacjentów z wytworzoną przetoką tętniczo-żylną leczonych metodą powtarzanych hemodializ na przestrzeganie zaleceń międzydializacyjnych” (2012r.)',
  ],
  'Dr n.med. Łukasz Przysło': [
    'Dr n.med. Łukasz Przysło to specjalista w dziedzinie epileptologii (od 2022 r.); neurologii dziecięcej(od 2017 r.) i pediatrii.',
    'Studia medyczne ukończył na Uniwersytecie Medycznym w Łodzi, a kilka lat później zdobył stopień doktora nauk medycznych(2009 r.). Ukończył również studia podyplomowe z Psychoonkologii na Uniwersytecie SWPS w Warszawie.',
    'Od 2005 r. pracuje w Centrum Opieki Paliatywnej dla dzieci w Łodzi jako neuropediatra a od 2014 r. pełni obowiązki kierownika w Klinice Neurologii Rozwojowej i Epileptologii ICZMP w Łodzi oraz zajmuje stanowisko adiunkta we wspomnianym Instytucie.',
    'Związany jest  z Centrum Medycznym „PoMoc” znajdującym się również w Łodzi.',
    'Dr Przysło to  autor oraz współautor klilkunastu oryginalnych artykułów naukowych (dotyczących m.in. opieki paliatywnej: „Nudności i wymioty  w pediatrycznej opiece paliatywnej; „Zapotrzebowanie na domową opiekę paliatywną nad dziećmi w województwie łódzkim” i wielu innych) oraz autor kilku rozdziałów w literaturze poświęconej neuropediatrii. Jest aktywnym uczestnikiem zjazdów i konferencji poświęconych neurologii dziecięcej. Należy do takich towarzystw naukowych jak: Polskie Towarzystwo Neurologów Dziecięcych, European Paediatric Neurology Society, The International Child Neurology Association oraz  International League Against Epile.',
    'Posiada  bogate doświadczenie (od 2015 r.) w prowadzeniu badań klinicznych jako główny badacz/współbadacz, w takich schorzeniach jak:',
    'Padaczka lekooporna( 2018 - 2022 r. oraz 2019 - 2022 r.) ;',
    'Spastyczność( 2015 -2017 r.)',
    'Zespół Draveta',
    'Stwardnienie rozsiane - (2015 r. - nadal)',
  ],
  'Dr n.med. Natalia Zawada-Kornalewicz': [
    'to doświadczona specjalistka w zakresie chorób wewnętrznych, diabetologii i endokrynologii.',
    'Przez wiele lat związana była z Kliniką Endokrynologii Szpitala im. S. Sterlinga, a przez kolejne lata z Kliniką Endokrynologii i Diabetologii Centralnego Szpitala Klinicznego Uniwersytetu Medycznego w Łodzi.',
    'Ukończyła studia medyczne jako absolwent Uniwersytetu Medycznego w Łodzi, a następnie uzyskała tytuł doktora nauk medycznych.',
    'Zajmuje stanowisko Krajowego Koordynatora badania klinicznego dot. Stosowania analogu somatostatyny w leczeniu akromegalii.',
    'Jest laureatką „Fundacji na Rzecz Nauki w Polsce” , „Operacji sukces” oraz kilkukrotną stypendystką macierzystego Uniwersytetu.',
    'Uczestniczyła w wielu stażach, w tym zagranicznych, m.in. w Klinice Endokrynologii Szpitala St Bartholomew’s Hospital, w Londynie czy Humanitas University w Mediolanie, oprócz tego jest autorem kilkudziesięciu oryginalnych prac naukowych.',
    'Należy do takich Towarzystw Naukowych jak m.in.: Polskie Towarzystwo Endokrynologiczne, Polskie Towarzystwo Neuroendokrynologii, Europejskie Towarzystwo Endokrynologiczne i Europejskiego Towarzystwo Neuroendokrynologicznego, Klub 30 - zrzeszający wiodących, młodych Endokrynologów w Polsce.',
    'Jest autorem kilkunastu publikacji naukowych obejmujących dziedzinę endokrynologii, w tym m.in.:',
    '„An evaluation of the effects of somatostatin analogue therapy in non-functioning pituitary adenomas in comparison to acromegaly” (2016r.)',
    '„The corellation between somatostatin receptors expression and octreotide treatment in non-functioning pituitary adenomas” (2016r.)',
    '„The expression of somatostatin receptor subtypes in immunohistochemistry and the response to somatostatin analogue therapy in non-functioning pituitary adenomas” (2019r.)',
    '„Somatostatin analogues therapy of clinically non-functioning pituitary adenomas- impact on tumour volume and visual field” (2018r.)',
  ],
  'Adam Juszczak': [
    'Dyrektor Zarządzający',
    'Właściciel i współtwórca AmiCare sp. z o.o. sp.k.',
    'Absolwent Uniwersytetu Wrocławskiego, Od 2003 r. aktywnie działający w branży medycznej. Otwarty na nowe wyzwania zarówno w AmiCare jak i w sporcie, bez którego nie wyobraża sobie życia. Zwolennik aktywnego stylu życia w towarzystwie rodziny i przyjaciół.',
    'Zakładając AmiCare chciał wykorzystać swoje doświadczenie w świecie medycyny by poprzez udział we współtworzeniu nowych cząsteczek, pomóc Pacjentom i ich rodzinom w pokonywaniu barier związanych z ciężkimi chorobami.',
    'Utrzymanie najwyższego poziomu opieki nad Pacjentami i bezpośredni z nimi kontakt jest dla niego i całego Zespołu AmiCare Centrum Medycznego priorytetem.',
    '„We help patients through science” - tak rozumie działanie AmiCare i jego rolę w międzynarodowej branży medycznej. Nie zapomina również o roli profilaktyki i holistycznego podejścia do zdrowia każdego człowieka, szukając nowych sposobów w pomaganiu. „Świat należy do młodzieży” to nie tylko jego powiedzenie, ale także idea pozwalająca mu szkolić w AmiCare studentów czy świeżo upieczonych absolwentów z dziedziny biotechnologii, farmacji itp.',
    'Jakość zarządzania i pracy całego Zespołu AmiCare Centrum Medycznego została bardzo pozytywnie zweryfikowana m.in. przez przedstawiciela U.S.FDA (Food and Drug Administration ze Stanów Zjednoczonych) w czasie inspekcji Ośrodka w 2023r.',
  ],
  'Anna Góra': [
    'Kierownik ośrodka badań klinicznych',
    'Absolwentka Uniwersytetu Medycznego w Łodzi. Od ponad 20 lat związana z sektorem ochrony zdrowia, gdzie zdobywała doświadczenie w obszarze organizacji pracy placówek medycznych, badań klinicznych oraz zarządzania zespołami.',
    'Przez wiele lat uczestniczyła w realizacji projektów badawczych, odpowiadając za koordynację pracy zespołów i zapewnienie sprawnego przebiegu procesów operacyjnych. Od 7 lat pełni funkcje kierownicze, skutecznie łącząc wiedzę organizacyjną z praktycznym doświadczeniem zdobytym w środowisku medycznym.',
    'W swojej pracy koncentruje się na budowaniu efektywnych zespołów, wysokiej jakości obsługi pacjentów oraz ciągłym doskonaleniu standardów funkcjonowania placówki. Ceni profesjonalizm, zaangażowanie i partnerskie relacje, które stanowią fundament skutecznej współpracy.',
    'Prywatnie pasjonuje się jazdą konną oraz ogrodnictwem. Wolny czas najchętniej spędza aktywnie, czerpiąc inspirację z kontaktu z naturą.',
  ],
  'Jakub Majka': [
    'Kierownik Centrum Medycznego ds. usług medycznych',
    'Student Zdrowia Publicznego na Uniwersytecie medycznym w Łodzi.',
    'Swoją przygodę zawodową rozpoczął właśnie w AmiCare Centrum Medycznym, gdzie od lipca 2022 roku został konsultantem ds. marketingu i zdrowia. Zajmował się akcjami marketingowymi oraz social mediami placówki. Dzięki swojemu zaangażowaniu po półtora roku pracy został koordynatorem ds. marketingu i zdrowa. Natomiast od kwietnia 2024 roku awansował na obecną funkcję w AmiCare. Dodatkowo Jakub interesuje się pierwszą pomocą - posiadam kurs Kwalifikowanej Pierwszej Pomocy(KPP).',
    'Natomiast w wolnej chwili z wielką przyjemnością chodzi na basen, żeby zresetować się od codziennych spraw.',
  ],
  'Marlena Serwacińska': [
    'Kierownik AmiCare Centum Medycznego.',
    'Absolwentka Uniwersytetu Medycznego w Łodzi.',
    'Od 2015 roku pracująca w szpitalach jako pielęgniarka, gdzie poznawała potrzeby oraz problemy pacjentów. Chęć szerszego pola pomocy osobą chorym pokierowała ją w badania kliniczne. Początkowo - pielęgniarka, następnie rozszerzała zakres swoich kompetencji w AmiCare Centrum Medycznym jako koordynatora aż do aktualnego stanowiska.',
    'Dzięki drodze, którą przeszła, stara się, aby opieka nad pacjentem zawsze była na najwyższym poziomie. Cały czas pogłębia i aktualizuje swoją wiedzę uczestnicząc w szkoleniach, kursach oraz kończąc w 2022 roku studia podyplomowe na kierunku Monitorowanie i koordynacja badań klinicznych.',
    'Najważniejszą wartością dla Marleny jest zdrowie, dlatego każdego dnia dba o siebie jak i o swoich bliskich. Regeneruje się wyjeżdżając z miasta i odkrywając ciekawe miejsca w najgłębszych zakątkach przyrody, aby kolejny tydzień rozpocząć z uśmiechem.',
  ],
  'Michał Bytomski': [
    'Prezes Zarządu, Właściciel i współtwórca AmiCare Centrum Medycznego',
    'Absolwent Akademii Morskiej w Szczecinie, Wykwalifikowany specjalista od lat działający w branży morskiej. (Prezes Alphatron Poland i THESTA.)',
    'Entuzjasta aktywnego i zdrowego stylu życia, doświadczony żeglarz, inspirujący do działania i odważnego sięgania po swoje marzenia.',
    'Dzięki swojemu doświadczeniu w zarządzaniu próbuje podnieść usługi medyczne AmiCare na coraz wyższy poziom, który nie tylko pozwoli sprostać współczesnym wymaganiom, ale określi nową drogę na przyszłość. Jako inżynier wie, że tylko poprzez konsekwencje działania, reagowanie na zmiany i jasne cele można jednocześnie pomagać Pacjentom jak i prowadzić do sukcesu Zespołu.',
  ],
  'Dorota Sobczyk-Cłapa': [
    'Koordynator badań klinicznych',
    'Ukończyła Uniwersytet Łódzki zdobywając tytuł magistra chemii, a także Policealne Studium Farmaceutyczne pozwalające na prace w aptece jako technik farmaceutyczny.',
    'Od początku drogi zawodowej jako koordynator badań klinicznych, czerpię wiedzę od najlepszych lekarzy specjalistów oraz doświadczonych koordynatorów i pielęgniarek.',
    'Kontakt z pacjentem, dbanie o jego dobro w czasie udziału w badaniu klinicznym, współpraca z lekarzem oraz  samodoskonalenie zawodowe, to dla Doroty kluczowe wartości, aby być dobrym koordynatorem. Prywatnie - uśmiechnięta mama, energicznego Jasia oraz miłośniczka Tatr.',
  ],
  'Karolina Szcześniak': [
    'Koordynator badań klinicznych',
    'W 2011 roku rozpoczęła swoją przygodę w badaniach klinicznych przechodząc przez rożne stanowiska pracy natomiast koordynatorem badań klinicznych jest od 2018 roku po dzień dzisiejszy.',
    'Stale się rozwija i czerpię wiedzę od najlepszych specjalistów oraz zespołu badawczego jak również uczestnicząc w licznych szkoleniach i kursach.',
    'Prywatnie jest szczęśliwą żoną i mamą dwóch wspaniałych synów. Bardzo lubi podróżować i interesuje się siatkówką.',
  ],
  'Maria Smul': [
    'Koordynator badań klinicznych',
    'Z wykształcenia - magister inżynier Biotechnologii, absolwentka Politechniki Łódzkiej.',
    'Posiada wieloletnie doświadczenie w badaniach klinicznych, głównie : gastroenterologicznych, kardiologicznych, pulmonologicznych, dermatologicznych, reumatologicznych, diabetologicznych, układu ruchu oraz neurologicznych. W firmie AmiCare  Centrum Medycznym pracuje od 2021 roku.',
    'Prywatnie lubi długie spacery, podziwiając piękno przyrody. Maria w wolnym czasie jeździ na wycieczki rowerowe i spędza czas z rodziną.',
  ],
  'lek. Karolina Kabot': [
    'lek. Karolina Kabot - Anestezjolog',
  ],
  'lek. Leszek Weber': [
    'lek. Leszek Weber - Anestezjolog',
  ],
  'Prof. dr hab. n.med. Joanna Jerzyńska': [
    'Prof. dr hab. n.med.  Joanna Jerzyńska  to doświadczony lekarz specjalista w zakresie pediatrii oraz alergologii.',
    'Studia medyczne ukończyła na Akademii Medycznej w Łodzi, a w 2001r. zdobyła tytuł specjalisty w dziedzinie pediatrii( I st.) jak również tytuł doktora nauk medycznych.',
    'W 2006 roku uzyskała II st. specjalisty w dziedzinie pediatrii,  a sześć lat później w zakresie alergologii(2013 r.)',
    'W 2017 roku zdobyła tytuł doktora habilitowanego nauk medycznych Uniwersytetu Medycznego w Łodzi, a następnie w 2019 r. nadano jej tytuł profesora uczelni.',
    'W latach 1997 - 2005 sprawowała funkcję Młodszego Asystenta na Oddziale Klinicznym Interny Dziecięcej i Alergologii Instytutu Pediatrii UM w Łodzi, przez kolejne lata (2005 - 2015) obejmowała stanowisko Starszego Asystenta na Oddziale Alergologii i Interny Dziecięcej Wojewódzkiego Szpitala Specjalistycznego im.M Kopernika w Łodzi.',
    'W 2019 r. pełniła obowiązki kierownika na Oddziale Klinicznym Interny Dziecięcej i Alergologii III Katedry Pediatrii UM w Łodzi, a od 2015 r. niezmiennie sprawuje funkcję Starszego Asystenta na Oddziale Klinicznym Interny Dziecięcej i Alergologii Wojewódzkiego Wielospecjalistycznego Centrum Onkologii i Traumatologii im. M Kopernika, gdzie szczególnie  zajmuje się dziećmi cierpiącymi na astmę oskrzelową oraz choroby alergiczne.',
    'Od 1999 roku współpracuje z Uniwersytetem Columbia w Nowym Jorku, co przyczyniło się m.in. do pracy nad nowatorskim badaniem dotyczącym alergii na karaluchy w Polsce.',
    'Od 2018 roku sprawuje stanowisko Przewodniczącej Łódzkiego Oddziału Polskiego Towarzystwa Alergologicznego.  Jest autorką & współautorką kilkunastu publikacji naukowych obejmujących szeroko pojętą dziedzinę alergologii, w tym m.in.:',
    '„Omalizumab as a new therapeutic approach for children with severe asthma: a case report” (2015r.)',
    '„Effect of regular training on lung function in adolescents” (2019r.)',
    '„Ocena surowiczego stężenia 25(OH)D u dzieci z nawracającymi infekcjami z regionu łódzkiego” (2019r.)',
    '„Common variable immunodeficiency in an 11-year-old girl - a case report” (2020r.)',
    'Doświadczenie w prowadzeniu badań klinicznych jako badacz/współbadacz posiada od 2001 r., w takich schorzeniach jak m.in.:',
    'Astma( od 2001r.)',
    'Cukrzyca typu II ( 2016r.)',
    'Alergiczny nieżyt nosa(2019r. - nadal)',
    'Astma i Sezonowe alergiczne zapalenie błony śluzowej nosa i spojówek(2015r.)',
    'Z Centrum Medycznym AmiCare współpracuje jako Główny Badacz w swojej specjalizacji nieprzerwanie od 2021r.',
  ],
  'Angelika Jurkiewicz': [
    'Pielęgniarka badań klinicznych',
    'Pielęgniarka z doświadczeniem zdobytym w pracy z pacjentami pediatrycznymi. Doświadczenie zawodowe rozwijała m.in. w Instytucie Centrum Zdrowia Matki Polki w Łodzi.',
    'W swojej codziennej pracy łączy wiedzę medyczną z empatią i indywidualnym podejściem do pacjenta. Szczególną uwagę poświęca budowaniu poczucia bezpieczeństwa i komfortu uczestników badań klinicznych oraz wysokim standardom opieki.',
  ],
  'Hubert Sadowski': [
    'Pielęgniarz',
    'Pielęgniarz z doświadczeniem zdobytym w warunkach Szpitalnego Oddziału Ratunkowego. W AmiCare Hubert łączy techniczną precyzję i opanowanie z empatią. Jego priorytetem jest to, by każdy pacjent czuł się w procesie badania bezpiecznie, komfortowo i - co najważniejsze - słyszany. Wierzy, że indywidualne podejście to klucz do zaufania, które w badaniach klinicznych jest fundamentem.',
    'Prywatnie Hubert to miłośnik dalekich podróży, który najchętniej odkrywa smaki i kulturę Azji. Energię do działania czerpie z treningów na siłowni, a wolne wieczory spędza przy dobrej książce, planszówkach lub doskonaląc swoje umiejętności kulinarne.',
  ],
};
